### YamlMime:ManagedReference
items:
- uid: OpenSpartan.Grunt.Models.GruntConfiguration
  commentId: T:OpenSpartan.Grunt.Models.GruntConfiguration
  id: GruntConfiguration
  children:
  - OpenSpartan.Grunt.Models.GruntConfiguration.#ctor
  - OpenSpartan.Grunt.Models.GruntConfiguration.ClearanceToken
  langs:
  - csharp
  name: GruntConfiguration
  nameWithType: OpenSpartan.Grunt.Models.GruntConfiguration
  fullName: OpenSpartan.Grunt.Models.GruntConfiguration
  type: Class
  assemblies:
  - OpenSpartan.Grunt
  namespace: OpenSpartan.Grunt.Models
  syntax:
    content: public class GruntConfiguration
    content.csharp: public class GruntConfiguration
  inheritance:
  - System.Object
  implements: []
  inheritedMembers: []
  modifiers.csharp:
  - public
  monikers:
  - net6.0
  _op_AssemblyMonikerMapping:
    OpenSpartan.Grunt:
    - net6.0
- uid: OpenSpartan.Grunt.Models.GruntConfiguration.#ctor
  commentId: M:OpenSpartan.Grunt.Models.GruntConfiguration.#ctor
  id: '#ctor'
  parent: OpenSpartan.Grunt.Models.GruntConfiguration
  langs:
  - csharp
  name: GruntConfiguration()
  nameWithType: GruntConfiguration.GruntConfiguration()
  fullName: OpenSpartan.Grunt.Models.GruntConfiguration.GruntConfiguration()
  type: Constructor
  assemblies:
  - OpenSpartan.Grunt
  namespace: OpenSpartan.Grunt.Models
  syntax:
    content: public GruntConfiguration ();
    parameters: []
    content.csharp: public GruntConfiguration ();
  overload: OpenSpartan.Grunt.Models.GruntConfiguration.#ctor*
  exceptions: []
  modifiers.csharp:
  - public
  monikers:
  - net6.0
- uid: OpenSpartan.Grunt.Models.GruntConfiguration.ClearanceToken
  commentId: P:OpenSpartan.Grunt.Models.GruntConfiguration.ClearanceToken
  id: ClearanceToken
  parent: OpenSpartan.Grunt.Models.GruntConfiguration
  langs:
  - csharp
  name: ClearanceToken
  nameWithType: GruntConfiguration.ClearanceToken
  fullName: OpenSpartan.Grunt.Models.GruntConfiguration.ClearanceToken
  type: Property
  assemblies:
  - OpenSpartan.Grunt
  namespace: OpenSpartan.Grunt.Models
  syntax:
    content: >-
      [[System.Text.Json.Serialization.JsonPropertyName("clearance_token")]]

      public string ClearanceToken { get; set; }
    return:
      type: System.String
      description: ''
    content.csharp: >-
      [[System.Text.Json.Serialization.JsonPropertyName("clearance_token")]]

      public string ClearanceToken { get; set; }
  overload: OpenSpartan.Grunt.Models.GruntConfiguration.ClearanceToken*
  exceptions: []
  attributes:
  - type: '[System.Text.Json.Serialization.JsonPropertyNameAttribute'
  modifiers.csharp:
  - public
  - get
  - set
  monikers:
  - net6.0
references:
- uid: OpenSpartan.Grunt.Models
  commentId: N:OpenSpartan.Grunt.Models
  isExternal: false
  name: OpenSpartan.Grunt.Models
  nameWithType: OpenSpartan.Grunt.Models
  fullName: OpenSpartan.Grunt.Models
  type: namespace
- uid: System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: OpenSpartan.Grunt.Models.GruntConfiguration.#ctor
  parent: OpenSpartan.Grunt.Models.GruntConfiguration
  isExternal: false
  name: GruntConfiguration()
  nameWithType: GruntConfiguration.GruntConfiguration()
  fullName: OpenSpartan.Grunt.Models.GruntConfiguration.GruntConfiguration()
  type: constructor
- uid: OpenSpartan.Grunt.Models.GruntConfiguration.ClearanceToken
  parent: OpenSpartan.Grunt.Models.GruntConfiguration
  isExternal: false
  name: ClearanceToken
  nameWithType: GruntConfiguration.ClearanceToken
  fullName: OpenSpartan.Grunt.Models.GruntConfiguration.ClearanceToken
  type: property
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: OpenSpartan.Grunt.Models.GruntConfiguration.#ctor*
  commentId: Overload:OpenSpartan.Grunt.Models.GruntConfiguration.#ctor
  parent: OpenSpartan.Grunt.Models.GruntConfiguration
  isExternal: false
  name: GruntConfiguration
  nameWithType: GruntConfiguration.GruntConfiguration
  fullName: OpenSpartan.Grunt.Models.GruntConfiguration.GruntConfiguration
  monikers:
  - net6.0
  type: constructor
- uid: OpenSpartan.Grunt.Models.GruntConfiguration.ClearanceToken*
  commentId: Overload:OpenSpartan.Grunt.Models.GruntConfiguration.ClearanceToken
  parent: OpenSpartan.Grunt.Models.GruntConfiguration
  isExternal: false
  name: ClearanceToken
  nameWithType: GruntConfiguration.ClearanceToken
  fullName: OpenSpartan.Grunt.Models.GruntConfiguration.ClearanceToken
  monikers:
  - net6.0
  type: property
