### YamlMime:ManagedReference
items:
- uid: OpenSpartan.Grunt.Models.HaloInfinite.InGameItemConfiguration
  commentId: T:OpenSpartan.Grunt.Models.HaloInfinite.InGameItemConfiguration
  id: InGameItemConfiguration
  children:
  - OpenSpartan.Grunt.Models.HaloInfinite.InGameItemConfiguration.#ctor
  - OpenSpartan.Grunt.Models.HaloInfinite.InGameItemConfiguration.ConfigurationId
  - OpenSpartan.Grunt.Models.HaloInfinite.InGameItemConfiguration.ConfigurationPath
  langs:
  - csharp
  name: InGameItemConfiguration
  nameWithType: OpenSpartan.Grunt.Models.HaloInfinite.InGameItemConfiguration
  fullName: OpenSpartan.Grunt.Models.HaloInfinite.InGameItemConfiguration
  type: Class
  assemblies:
  - OpenSpartan.Grunt
  namespace: OpenSpartan.Grunt.Models.HaloInfinite
  syntax:
    content: >-
      [[OpenSpartan.Grunt.Models.IsAutomaticallySerializable]]

      public class InGameItemConfiguration
    content.csharp: >-
      [[OpenSpartan.Grunt.Models.IsAutomaticallySerializable]]

      public class InGameItemConfiguration
  inheritance:
  - System.Object
  implements: []
  inheritedMembers: []
  attributes:
  - type: '[OpenSpartan.Grunt.Models.IsAutomaticallySerializable]Attribute'
  modifiers.csharp:
  - public
  monikers:
  - net6.0
  _op_AssemblyMonikerMapping:
    OpenSpartan.Grunt:
    - net6.0
- uid: OpenSpartan.Grunt.Models.HaloInfinite.InGameItemConfiguration.#ctor
  commentId: M:OpenSpartan.Grunt.Models.HaloInfinite.InGameItemConfiguration.#ctor
  id: '#ctor'
  parent: OpenSpartan.Grunt.Models.HaloInfinite.InGameItemConfiguration
  langs:
  - csharp
  name: InGameItemConfiguration()
  nameWithType: InGameItemConfiguration.InGameItemConfiguration()
  fullName: OpenSpartan.Grunt.Models.HaloInfinite.InGameItemConfiguration.InGameItemConfiguration()
  type: Constructor
  assemblies:
  - OpenSpartan.Grunt
  namespace: OpenSpartan.Grunt.Models.HaloInfinite
  syntax:
    content: public InGameItemConfiguration ();
    parameters: []
    content.csharp: public InGameItemConfiguration ();
  overload: OpenSpartan.Grunt.Models.HaloInfinite.InGameItemConfiguration.#ctor*
  exceptions: []
  modifiers.csharp:
  - public
  monikers:
  - net6.0
- uid: OpenSpartan.Grunt.Models.HaloInfinite.InGameItemConfiguration.ConfigurationId
  commentId: P:OpenSpartan.Grunt.Models.HaloInfinite.InGameItemConfiguration.ConfigurationId
  id: ConfigurationId
  parent: OpenSpartan.Grunt.Models.HaloInfinite.InGameItemConfiguration
  langs:
  - csharp
  name: ConfigurationId
  nameWithType: InGameItemConfiguration.ConfigurationId
  fullName: OpenSpartan.Grunt.Models.HaloInfinite.InGameItemConfiguration.ConfigurationId
  type: Property
  assemblies:
  - OpenSpartan.Grunt
  namespace: OpenSpartan.Grunt.Models.HaloInfinite
  syntax:
    content: public int ConfigurationId { get; set; }
    return:
      type: System.Int32
      description: ''
    content.csharp: public int ConfigurationId { get; set; }
  overload: OpenSpartan.Grunt.Models.HaloInfinite.InGameItemConfiguration.ConfigurationId*
  exceptions: []
  modifiers.csharp:
  - public
  - get
  - set
  monikers:
  - net6.0
- uid: OpenSpartan.Grunt.Models.HaloInfinite.InGameItemConfiguration.ConfigurationPath
  commentId: P:OpenSpartan.Grunt.Models.HaloInfinite.InGameItemConfiguration.ConfigurationPath
  id: ConfigurationPath
  parent: OpenSpartan.Grunt.Models.HaloInfinite.InGameItemConfiguration
  langs:
  - csharp
  name: ConfigurationPath
  nameWithType: InGameItemConfiguration.ConfigurationPath
  fullName: OpenSpartan.Grunt.Models.HaloInfinite.InGameItemConfiguration.ConfigurationPath
  type: Property
  assemblies:
  - OpenSpartan.Grunt
  namespace: OpenSpartan.Grunt.Models.HaloInfinite
  syntax:
    content: public string ConfigurationPath { get; set; }
    return:
      type: System.String
      description: ''
    content.csharp: public string ConfigurationPath { get; set; }
  overload: OpenSpartan.Grunt.Models.HaloInfinite.InGameItemConfiguration.ConfigurationPath*
  exceptions: []
  modifiers.csharp:
  - public
  - get
  - set
  monikers:
  - net6.0
references:
- uid: OpenSpartan.Grunt.Models.HaloInfinite
  commentId: N:OpenSpartan.Grunt.Models.HaloInfinite
  isExternal: false
  name: OpenSpartan.Grunt.Models.HaloInfinite
  nameWithType: OpenSpartan.Grunt.Models.HaloInfinite
  fullName: OpenSpartan.Grunt.Models.HaloInfinite
  type: namespace
- uid: System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: OpenSpartan.Grunt.Models.HaloInfinite.InGameItemConfiguration.#ctor
  parent: OpenSpartan.Grunt.Models.HaloInfinite.InGameItemConfiguration
  isExternal: false
  name: InGameItemConfiguration()
  nameWithType: InGameItemConfiguration.InGameItemConfiguration()
  fullName: OpenSpartan.Grunt.Models.HaloInfinite.InGameItemConfiguration.InGameItemConfiguration()
  type: constructor
- uid: OpenSpartan.Grunt.Models.HaloInfinite.InGameItemConfiguration.ConfigurationId
  parent: OpenSpartan.Grunt.Models.HaloInfinite.InGameItemConfiguration
  isExternal: false
  name: ConfigurationId
  nameWithType: InGameItemConfiguration.ConfigurationId
  fullName: OpenSpartan.Grunt.Models.HaloInfinite.InGameItemConfiguration.ConfigurationId
  type: property
- uid: System.Int32
  parent: System
  isExternal: true
  name: Int32
  nameWithType: Int32
  fullName: System.Int32
- uid: OpenSpartan.Grunt.Models.HaloInfinite.InGameItemConfiguration.ConfigurationPath
  parent: OpenSpartan.Grunt.Models.HaloInfinite.InGameItemConfiguration
  isExternal: false
  name: ConfigurationPath
  nameWithType: InGameItemConfiguration.ConfigurationPath
  fullName: OpenSpartan.Grunt.Models.HaloInfinite.InGameItemConfiguration.ConfigurationPath
  type: property
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: OpenSpartan.Grunt.Models.HaloInfinite.InGameItemConfiguration.#ctor*
  commentId: Overload:OpenSpartan.Grunt.Models.HaloInfinite.InGameItemConfiguration.#ctor
  parent: OpenSpartan.Grunt.Models.HaloInfinite.InGameItemConfiguration
  isExternal: false
  name: InGameItemConfiguration
  nameWithType: InGameItemConfiguration.InGameItemConfiguration
  fullName: OpenSpartan.Grunt.Models.HaloInfinite.InGameItemConfiguration.InGameItemConfiguration
  monikers:
  - net6.0
  type: constructor
- uid: OpenSpartan.Grunt.Models.HaloInfinite.InGameItemConfiguration.ConfigurationId*
  commentId: Overload:OpenSpartan.Grunt.Models.HaloInfinite.InGameItemConfiguration.ConfigurationId
  parent: OpenSpartan.Grunt.Models.HaloInfinite.InGameItemConfiguration
  isExternal: false
  name: ConfigurationId
  nameWithType: InGameItemConfiguration.ConfigurationId
  fullName: OpenSpartan.Grunt.Models.HaloInfinite.InGameItemConfiguration.ConfigurationId
  monikers:
  - net6.0
  type: property
- uid: OpenSpartan.Grunt.Models.HaloInfinite.InGameItemConfiguration.ConfigurationPath*
  commentId: Overload:OpenSpartan.Grunt.Models.HaloInfinite.InGameItemConfiguration.ConfigurationPath
  parent: OpenSpartan.Grunt.Models.HaloInfinite.InGameItemConfiguration
  isExternal: false
  name: ConfigurationPath
  nameWithType: InGameItemConfiguration.ConfigurationPath
  fullName: OpenSpartan.Grunt.Models.HaloInfinite.InGameItemConfiguration.ConfigurationPath
  monikers:
  - net6.0
  type: property
