### YamlMime:ManagedReference
items:
- uid: OpenSpartan.Grunt.Models.HaloInfinite.ApiIngress.RetryPolicy
  commentId: T:OpenSpartan.Grunt.Models.HaloInfinite.ApiIngress.RetryPolicy
  id: RetryPolicy
  children:
  - OpenSpartan.Grunt.Models.HaloInfinite.ApiIngress.RetryPolicy.#ctor
  - OpenSpartan.Grunt.Models.HaloInfinite.ApiIngress.RetryPolicy.RetryOptions
  - OpenSpartan.Grunt.Models.HaloInfinite.ApiIngress.RetryPolicy.RetryPolicyId
  - OpenSpartan.Grunt.Models.HaloInfinite.ApiIngress.RetryPolicy.TimeoutMs
  langs:
  - csharp
  name: RetryPolicy
  nameWithType: OpenSpartan.Grunt.Models.HaloInfinite.ApiIngress.RetryPolicy
  fullName: OpenSpartan.Grunt.Models.HaloInfinite.ApiIngress.RetryPolicy
  type: Class
  assemblies:
  - OpenSpartan.Grunt
  namespace: OpenSpartan.Grunt.Models.HaloInfinite.ApiIngress
  syntax:
    content: public class RetryPolicy
    content.csharp: public class RetryPolicy
  inheritance:
  - System.Object
  implements: []
  inheritedMembers: []
  modifiers.csharp:
  - public
  monikers:
  - net6.0
  _op_AssemblyMonikerMapping:
    OpenSpartan.Grunt:
    - net6.0
- uid: OpenSpartan.Grunt.Models.HaloInfinite.ApiIngress.RetryPolicy.#ctor
  commentId: M:OpenSpartan.Grunt.Models.HaloInfinite.ApiIngress.RetryPolicy.#ctor
  id: '#ctor'
  parent: OpenSpartan.Grunt.Models.HaloInfinite.ApiIngress.RetryPolicy
  langs:
  - csharp
  name: RetryPolicy()
  nameWithType: RetryPolicy.RetryPolicy()
  fullName: OpenSpartan.Grunt.Models.HaloInfinite.ApiIngress.RetryPolicy.RetryPolicy()
  type: Constructor
  assemblies:
  - OpenSpartan.Grunt
  namespace: OpenSpartan.Grunt.Models.HaloInfinite.ApiIngress
  syntax:
    content: public RetryPolicy ();
    parameters: []
    content.csharp: public RetryPolicy ();
  overload: OpenSpartan.Grunt.Models.HaloInfinite.ApiIngress.RetryPolicy.#ctor*
  exceptions: []
  modifiers.csharp:
  - public
  monikers:
  - net6.0
- uid: OpenSpartan.Grunt.Models.HaloInfinite.ApiIngress.RetryPolicy.RetryOptions
  commentId: P:OpenSpartan.Grunt.Models.HaloInfinite.ApiIngress.RetryPolicy.RetryOptions
  id: RetryOptions
  parent: OpenSpartan.Grunt.Models.HaloInfinite.ApiIngress.RetryPolicy
  langs:
  - csharp
  name: RetryOptions
  nameWithType: RetryPolicy.RetryOptions
  fullName: OpenSpartan.Grunt.Models.HaloInfinite.ApiIngress.RetryPolicy.RetryOptions
  type: Property
  assemblies:
  - OpenSpartan.Grunt
  namespace: OpenSpartan.Grunt.Models.HaloInfinite.ApiIngress
  syntax:
    content: public OpenSpartan.Grunt.Models.HaloInfinite.ApiIngress.RetryOptions RetryOptions { get; set; }
    return:
      type: OpenSpartan.Grunt.Models.HaloInfinite.ApiIngress.RetryOptions
      description: ''
    content.csharp: public OpenSpartan.Grunt.Models.HaloInfinite.ApiIngress.RetryOptions RetryOptions { get; set; }
  overload: OpenSpartan.Grunt.Models.HaloInfinite.ApiIngress.RetryPolicy.RetryOptions*
  exceptions: []
  modifiers.csharp:
  - public
  - get
  - set
  monikers:
  - net6.0
- uid: OpenSpartan.Grunt.Models.HaloInfinite.ApiIngress.RetryPolicy.RetryPolicyId
  commentId: P:OpenSpartan.Grunt.Models.HaloInfinite.ApiIngress.RetryPolicy.RetryPolicyId
  id: RetryPolicyId
  parent: OpenSpartan.Grunt.Models.HaloInfinite.ApiIngress.RetryPolicy
  langs:
  - csharp
  name: RetryPolicyId
  nameWithType: RetryPolicy.RetryPolicyId
  fullName: OpenSpartan.Grunt.Models.HaloInfinite.ApiIngress.RetryPolicy.RetryPolicyId
  type: Property
  assemblies:
  - OpenSpartan.Grunt
  namespace: OpenSpartan.Grunt.Models.HaloInfinite.ApiIngress
  syntax:
    content: public string RetryPolicyId { get; set; }
    return:
      type: System.String
      description: ''
    content.csharp: public string RetryPolicyId { get; set; }
  overload: OpenSpartan.Grunt.Models.HaloInfinite.ApiIngress.RetryPolicy.RetryPolicyId*
  exceptions: []
  modifiers.csharp:
  - public
  - get
  - set
  monikers:
  - net6.0
- uid: OpenSpartan.Grunt.Models.HaloInfinite.ApiIngress.RetryPolicy.TimeoutMs
  commentId: P:OpenSpartan.Grunt.Models.HaloInfinite.ApiIngress.RetryPolicy.TimeoutMs
  id: TimeoutMs
  parent: OpenSpartan.Grunt.Models.HaloInfinite.ApiIngress.RetryPolicy
  langs:
  - csharp
  name: TimeoutMs
  nameWithType: RetryPolicy.TimeoutMs
  fullName: OpenSpartan.Grunt.Models.HaloInfinite.ApiIngress.RetryPolicy.TimeoutMs
  type: Property
  assemblies:
  - OpenSpartan.Grunt
  namespace: OpenSpartan.Grunt.Models.HaloInfinite.ApiIngress
  syntax:
    content: public int TimeoutMs { get; set; }
    return:
      type: System.Int32
      description: ''
    content.csharp: public int TimeoutMs { get; set; }
  overload: OpenSpartan.Grunt.Models.HaloInfinite.ApiIngress.RetryPolicy.TimeoutMs*
  exceptions: []
  modifiers.csharp:
  - public
  - get
  - set
  monikers:
  - net6.0
references:
- uid: OpenSpartan.Grunt.Models.HaloInfinite.ApiIngress
  commentId: N:OpenSpartan.Grunt.Models.HaloInfinite.ApiIngress
  isExternal: false
  name: OpenSpartan.Grunt.Models.HaloInfinite.ApiIngress
  nameWithType: OpenSpartan.Grunt.Models.HaloInfinite.ApiIngress
  fullName: OpenSpartan.Grunt.Models.HaloInfinite.ApiIngress
  type: namespace
- uid: System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: OpenSpartan.Grunt.Models.HaloInfinite.ApiIngress.RetryPolicy.#ctor
  parent: OpenSpartan.Grunt.Models.HaloInfinite.ApiIngress.RetryPolicy
  isExternal: false
  name: RetryPolicy()
  nameWithType: RetryPolicy.RetryPolicy()
  fullName: OpenSpartan.Grunt.Models.HaloInfinite.ApiIngress.RetryPolicy.RetryPolicy()
  type: constructor
- uid: OpenSpartan.Grunt.Models.HaloInfinite.ApiIngress.RetryPolicy.RetryOptions
  parent: OpenSpartan.Grunt.Models.HaloInfinite.ApiIngress.RetryPolicy
  isExternal: false
  name: RetryOptions
  nameWithType: RetryPolicy.RetryOptions
  fullName: OpenSpartan.Grunt.Models.HaloInfinite.ApiIngress.RetryPolicy.RetryOptions
  type: property
- uid: OpenSpartan.Grunt.Models.HaloInfinite.ApiIngress.RetryOptions
  parent: OpenSpartan.Grunt.Models.HaloInfinite.ApiIngress
  isExternal: false
  name: RetryOptions
  nameWithType: RetryOptions
  fullName: OpenSpartan.Grunt.Models.HaloInfinite.ApiIngress.RetryOptions
- uid: OpenSpartan.Grunt.Models.HaloInfinite.ApiIngress.RetryPolicy.RetryPolicyId
  parent: OpenSpartan.Grunt.Models.HaloInfinite.ApiIngress.RetryPolicy
  isExternal: false
  name: RetryPolicyId
  nameWithType: RetryPolicy.RetryPolicyId
  fullName: OpenSpartan.Grunt.Models.HaloInfinite.ApiIngress.RetryPolicy.RetryPolicyId
  type: property
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: OpenSpartan.Grunt.Models.HaloInfinite.ApiIngress.RetryPolicy.TimeoutMs
  parent: OpenSpartan.Grunt.Models.HaloInfinite.ApiIngress.RetryPolicy
  isExternal: false
  name: TimeoutMs
  nameWithType: RetryPolicy.TimeoutMs
  fullName: OpenSpartan.Grunt.Models.HaloInfinite.ApiIngress.RetryPolicy.TimeoutMs
  type: property
- uid: System.Int32
  parent: System
  isExternal: true
  name: Int32
  nameWithType: Int32
  fullName: System.Int32
- uid: OpenSpartan.Grunt.Models.HaloInfinite.ApiIngress.RetryPolicy.#ctor*
  commentId: Overload:OpenSpartan.Grunt.Models.HaloInfinite.ApiIngress.RetryPolicy.#ctor
  parent: OpenSpartan.Grunt.Models.HaloInfinite.ApiIngress.RetryPolicy
  isExternal: false
  name: RetryPolicy
  nameWithType: RetryPolicy.RetryPolicy
  fullName: OpenSpartan.Grunt.Models.HaloInfinite.ApiIngress.RetryPolicy.RetryPolicy
  monikers:
  - net6.0
  type: constructor
- uid: OpenSpartan.Grunt.Models.HaloInfinite.ApiIngress.RetryPolicy.RetryOptions*
  commentId: Overload:OpenSpartan.Grunt.Models.HaloInfinite.ApiIngress.RetryPolicy.RetryOptions
  parent: OpenSpartan.Grunt.Models.HaloInfinite.ApiIngress.RetryPolicy
  isExternal: false
  name: RetryOptions
  nameWithType: RetryPolicy.RetryOptions
  fullName: OpenSpartan.Grunt.Models.HaloInfinite.ApiIngress.RetryPolicy.RetryOptions
  monikers:
  - net6.0
  type: property
- uid: OpenSpartan.Grunt.Models.HaloInfinite.ApiIngress.RetryPolicy.RetryPolicyId*
  commentId: Overload:OpenSpartan.Grunt.Models.HaloInfinite.ApiIngress.RetryPolicy.RetryPolicyId
  parent: OpenSpartan.Grunt.Models.HaloInfinite.ApiIngress.RetryPolicy
  isExternal: false
  name: RetryPolicyId
  nameWithType: RetryPolicy.RetryPolicyId
  fullName: OpenSpartan.Grunt.Models.HaloInfinite.ApiIngress.RetryPolicy.RetryPolicyId
  monikers:
  - net6.0
  type: property
- uid: OpenSpartan.Grunt.Models.HaloInfinite.ApiIngress.RetryPolicy.TimeoutMs*
  commentId: Overload:OpenSpartan.Grunt.Models.HaloInfinite.ApiIngress.RetryPolicy.TimeoutMs
  parent: OpenSpartan.Grunt.Models.HaloInfinite.ApiIngress.RetryPolicy
  isExternal: false
  name: TimeoutMs
  nameWithType: RetryPolicy.TimeoutMs
  fullName: OpenSpartan.Grunt.Models.HaloInfinite.ApiIngress.RetryPolicy.TimeoutMs
  monikers:
  - net6.0
  type: property
