### YamlMime:ManagedReference
items:
- uid: OpenSpartan.Grunt.Models.HaloInfinite.MicrosoftStoreTitleConfiguration
  commentId: T:OpenSpartan.Grunt.Models.HaloInfinite.MicrosoftStoreTitleConfiguration
  id: MicrosoftStoreTitleConfiguration
  children:
  - OpenSpartan.Grunt.Models.HaloInfinite.MicrosoftStoreTitleConfiguration.#ctor
  - OpenSpartan.Grunt.Models.HaloInfinite.MicrosoftStoreTitleConfiguration.hi
  - OpenSpartan.Grunt.Models.HaloInfinite.MicrosoftStoreTitleConfiguration.hi343
  langs:
  - csharp
  name: MicrosoftStoreTitleConfiguration
  nameWithType: OpenSpartan.Grunt.Models.HaloInfinite.MicrosoftStoreTitleConfiguration
  fullName: OpenSpartan.Grunt.Models.HaloInfinite.MicrosoftStoreTitleConfiguration
  type: Class
  assemblies:
  - OpenSpartan.Grunt
  namespace: OpenSpartan.Grunt.Models.HaloInfinite
  syntax:
    content: >-
      [[OpenSpartan.Grunt.Models.IsAutomaticallySerializable]]

      public class MicrosoftStoreTitleConfiguration
    content.csharp: >-
      [[OpenSpartan.Grunt.Models.IsAutomaticallySerializable]]

      public class MicrosoftStoreTitleConfiguration
  inheritance:
  - System.Object
  implements: []
  inheritedMembers: []
  attributes:
  - type: '[OpenSpartan.Grunt.Models.IsAutomaticallySerializable]Attribute'
  modifiers.csharp:
  - public
  monikers:
  - net6.0
  _op_AssemblyMonikerMapping:
    OpenSpartan.Grunt:
    - net6.0
- uid: OpenSpartan.Grunt.Models.HaloInfinite.MicrosoftStoreTitleConfiguration.#ctor
  commentId: M:OpenSpartan.Grunt.Models.HaloInfinite.MicrosoftStoreTitleConfiguration.#ctor
  id: '#ctor'
  parent: OpenSpartan.Grunt.Models.HaloInfinite.MicrosoftStoreTitleConfiguration
  langs:
  - csharp
  name: MicrosoftStoreTitleConfiguration()
  nameWithType: MicrosoftStoreTitleConfiguration.MicrosoftStoreTitleConfiguration()
  fullName: OpenSpartan.Grunt.Models.HaloInfinite.MicrosoftStoreTitleConfiguration.MicrosoftStoreTitleConfiguration()
  type: Constructor
  assemblies:
  - OpenSpartan.Grunt
  namespace: OpenSpartan.Grunt.Models.HaloInfinite
  syntax:
    content: public MicrosoftStoreTitleConfiguration ();
    parameters: []
    content.csharp: public MicrosoftStoreTitleConfiguration ();
  overload: OpenSpartan.Grunt.Models.HaloInfinite.MicrosoftStoreTitleConfiguration.#ctor*
  exceptions: []
  modifiers.csharp:
  - public
  monikers:
  - net6.0
- uid: OpenSpartan.Grunt.Models.HaloInfinite.MicrosoftStoreTitleConfiguration.hi
  commentId: P:OpenSpartan.Grunt.Models.HaloInfinite.MicrosoftStoreTitleConfiguration.hi
  id: hi
  parent: OpenSpartan.Grunt.Models.HaloInfinite.MicrosoftStoreTitleConfiguration
  langs:
  - csharp
  name: hi
  nameWithType: MicrosoftStoreTitleConfiguration.hi
  fullName: OpenSpartan.Grunt.Models.HaloInfinite.MicrosoftStoreTitleConfiguration.hi
  type: Property
  assemblies:
  - OpenSpartan.Grunt
  namespace: OpenSpartan.Grunt.Models.HaloInfinite
  syntax:
    content: public OpenSpartan.Grunt.Models.HaloInfinite.HaloInfiniteMicrosoftStoreTitle hi { get; set; }
    return:
      type: OpenSpartan.Grunt.Models.HaloInfinite.HaloInfiniteMicrosoftStoreTitle
      description: ''
    content.csharp: public OpenSpartan.Grunt.Models.HaloInfinite.HaloInfiniteMicrosoftStoreTitle hi { get; set; }
  overload: OpenSpartan.Grunt.Models.HaloInfinite.MicrosoftStoreTitleConfiguration.hi*
  exceptions: []
  modifiers.csharp:
  - public
  - get
  - set
  monikers:
  - net6.0
- uid: OpenSpartan.Grunt.Models.HaloInfinite.MicrosoftStoreTitleConfiguration.hi343
  commentId: P:OpenSpartan.Grunt.Models.HaloInfinite.MicrosoftStoreTitleConfiguration.hi343
  id: hi343
  parent: OpenSpartan.Grunt.Models.HaloInfinite.MicrosoftStoreTitleConfiguration
  langs:
  - csharp
  name: hi343
  nameWithType: MicrosoftStoreTitleConfiguration.hi343
  fullName: OpenSpartan.Grunt.Models.HaloInfinite.MicrosoftStoreTitleConfiguration.hi343
  type: Property
  assemblies:
  - OpenSpartan.Grunt
  namespace: OpenSpartan.Grunt.Models.HaloInfinite
  syntax:
    content: public OpenSpartan.Grunt.Models.HaloInfinite.HaloInfinite343MicrosoftStoreTitle hi343 { get; set; }
    return:
      type: OpenSpartan.Grunt.Models.HaloInfinite.HaloInfinite343MicrosoftStoreTitle
      description: ''
    content.csharp: public OpenSpartan.Grunt.Models.HaloInfinite.HaloInfinite343MicrosoftStoreTitle hi343 { get; set; }
  overload: OpenSpartan.Grunt.Models.HaloInfinite.MicrosoftStoreTitleConfiguration.hi343*
  exceptions: []
  modifiers.csharp:
  - public
  - get
  - set
  monikers:
  - net6.0
references:
- uid: OpenSpartan.Grunt.Models.HaloInfinite
  commentId: N:OpenSpartan.Grunt.Models.HaloInfinite
  isExternal: false
  name: OpenSpartan.Grunt.Models.HaloInfinite
  nameWithType: OpenSpartan.Grunt.Models.HaloInfinite
  fullName: OpenSpartan.Grunt.Models.HaloInfinite
  type: namespace
- uid: System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: OpenSpartan.Grunt.Models.HaloInfinite.MicrosoftStoreTitleConfiguration.#ctor
  parent: OpenSpartan.Grunt.Models.HaloInfinite.MicrosoftStoreTitleConfiguration
  isExternal: false
  name: MicrosoftStoreTitleConfiguration()
  nameWithType: MicrosoftStoreTitleConfiguration.MicrosoftStoreTitleConfiguration()
  fullName: OpenSpartan.Grunt.Models.HaloInfinite.MicrosoftStoreTitleConfiguration.MicrosoftStoreTitleConfiguration()
  type: constructor
- uid: OpenSpartan.Grunt.Models.HaloInfinite.MicrosoftStoreTitleConfiguration.hi
  parent: OpenSpartan.Grunt.Models.HaloInfinite.MicrosoftStoreTitleConfiguration
  isExternal: false
  name: hi
  nameWithType: MicrosoftStoreTitleConfiguration.hi
  fullName: OpenSpartan.Grunt.Models.HaloInfinite.MicrosoftStoreTitleConfiguration.hi
  type: property
- uid: OpenSpartan.Grunt.Models.HaloInfinite.HaloInfiniteMicrosoftStoreTitle
  parent: OpenSpartan.Grunt.Models.HaloInfinite
  isExternal: false
  name: HaloInfiniteMicrosoftStoreTitle
  nameWithType: HaloInfiniteMicrosoftStoreTitle
  fullName: OpenSpartan.Grunt.Models.HaloInfinite.HaloInfiniteMicrosoftStoreTitle
- uid: OpenSpartan.Grunt.Models.HaloInfinite.MicrosoftStoreTitleConfiguration.hi343
  parent: OpenSpartan.Grunt.Models.HaloInfinite.MicrosoftStoreTitleConfiguration
  isExternal: false
  name: hi343
  nameWithType: MicrosoftStoreTitleConfiguration.hi343
  fullName: OpenSpartan.Grunt.Models.HaloInfinite.MicrosoftStoreTitleConfiguration.hi343
  type: property
- uid: OpenSpartan.Grunt.Models.HaloInfinite.HaloInfinite343MicrosoftStoreTitle
  parent: OpenSpartan.Grunt.Models.HaloInfinite
  isExternal: false
  name: HaloInfinite343MicrosoftStoreTitle
  nameWithType: HaloInfinite343MicrosoftStoreTitle
  fullName: OpenSpartan.Grunt.Models.HaloInfinite.HaloInfinite343MicrosoftStoreTitle
- uid: OpenSpartan.Grunt.Models.HaloInfinite.MicrosoftStoreTitleConfiguration.#ctor*
  commentId: Overload:OpenSpartan.Grunt.Models.HaloInfinite.MicrosoftStoreTitleConfiguration.#ctor
  parent: OpenSpartan.Grunt.Models.HaloInfinite.MicrosoftStoreTitleConfiguration
  isExternal: false
  name: MicrosoftStoreTitleConfiguration
  nameWithType: MicrosoftStoreTitleConfiguration.MicrosoftStoreTitleConfiguration
  fullName: OpenSpartan.Grunt.Models.HaloInfinite.MicrosoftStoreTitleConfiguration.MicrosoftStoreTitleConfiguration
  monikers:
  - net6.0
  type: constructor
- uid: OpenSpartan.Grunt.Models.HaloInfinite.MicrosoftStoreTitleConfiguration.hi*
  commentId: Overload:OpenSpartan.Grunt.Models.HaloInfinite.MicrosoftStoreTitleConfiguration.hi
  parent: OpenSpartan.Grunt.Models.HaloInfinite.MicrosoftStoreTitleConfiguration
  isExternal: false
  name: hi
  nameWithType: MicrosoftStoreTitleConfiguration.hi
  fullName: OpenSpartan.Grunt.Models.HaloInfinite.MicrosoftStoreTitleConfiguration.hi
  monikers:
  - net6.0
  type: property
- uid: OpenSpartan.Grunt.Models.HaloInfinite.MicrosoftStoreTitleConfiguration.hi343*
  commentId: Overload:OpenSpartan.Grunt.Models.HaloInfinite.MicrosoftStoreTitleConfiguration.hi343
  parent: OpenSpartan.Grunt.Models.HaloInfinite.MicrosoftStoreTitleConfiguration
  isExternal: false
  name: hi343
  nameWithType: MicrosoftStoreTitleConfiguration.hi343
  fullName: OpenSpartan.Grunt.Models.HaloInfinite.MicrosoftStoreTitleConfiguration.hi343
  monikers:
  - net6.0
  type: property
