### YamlMime:ManagedReference
items:
- uid: OpenSpartan.Grunt.Models.HaloInfinite.Configuration
  commentId: T:OpenSpartan.Grunt.Models.HaloInfinite.Configuration
  id: Configuration
  children:
  - OpenSpartan.Grunt.Models.HaloInfinite.Configuration.#ctor
  - OpenSpartan.Grunt.Models.HaloInfinite.Configuration.ConfigurationId
  - OpenSpartan.Grunt.Models.HaloInfinite.Configuration.ConfigurationPath
  langs:
  - csharp
  name: Configuration
  nameWithType: OpenSpartan.Grunt.Models.HaloInfinite.Configuration
  fullName: OpenSpartan.Grunt.Models.HaloInfinite.Configuration
  type: Class
  assemblies:
  - OpenSpartan.Grunt
  namespace: OpenSpartan.Grunt.Models.HaloInfinite
  syntax:
    content: >-
      [[OpenSpartan.Grunt.Models.IsAutomaticallySerializable]]

      public class Configuration
    content.csharp: >-
      [[OpenSpartan.Grunt.Models.IsAutomaticallySerializable]]

      public class Configuration
  inheritance:
  - System.Object
  implements: []
  inheritedMembers: []
  attributes:
  - type: '[OpenSpartan.Grunt.Models.IsAutomaticallySerializable]Attribute'
  modifiers.csharp:
  - public
  monikers:
  - net6.0
  _op_AssemblyMonikerMapping:
    OpenSpartan.Grunt:
    - net6.0
- uid: OpenSpartan.Grunt.Models.HaloInfinite.Configuration.#ctor
  commentId: M:OpenSpartan.Grunt.Models.HaloInfinite.Configuration.#ctor
  id: '#ctor'
  parent: OpenSpartan.Grunt.Models.HaloInfinite.Configuration
  langs:
  - csharp
  name: Configuration()
  nameWithType: Configuration.Configuration()
  fullName: OpenSpartan.Grunt.Models.HaloInfinite.Configuration.Configuration()
  type: Constructor
  assemblies:
  - OpenSpartan.Grunt
  namespace: OpenSpartan.Grunt.Models.HaloInfinite
  syntax:
    content: public Configuration ();
    parameters: []
    content.csharp: public Configuration ();
  overload: OpenSpartan.Grunt.Models.HaloInfinite.Configuration.#ctor*
  exceptions: []
  modifiers.csharp:
  - public
  monikers:
  - net6.0
- uid: OpenSpartan.Grunt.Models.HaloInfinite.Configuration.ConfigurationId
  commentId: P:OpenSpartan.Grunt.Models.HaloInfinite.Configuration.ConfigurationId
  id: ConfigurationId
  parent: OpenSpartan.Grunt.Models.HaloInfinite.Configuration
  langs:
  - csharp
  name: ConfigurationId
  nameWithType: Configuration.ConfigurationId
  fullName: OpenSpartan.Grunt.Models.HaloInfinite.Configuration.ConfigurationId
  type: Property
  assemblies:
  - OpenSpartan.Grunt
  namespace: OpenSpartan.Grunt.Models.HaloInfinite
  syntax:
    content: public int ConfigurationId { get; set; }
    return:
      type: System.Int32
      description: ''
    content.csharp: public int ConfigurationId { get; set; }
  overload: OpenSpartan.Grunt.Models.HaloInfinite.Configuration.ConfigurationId*
  exceptions: []
  modifiers.csharp:
  - public
  - get
  - set
  monikers:
  - net6.0
- uid: OpenSpartan.Grunt.Models.HaloInfinite.Configuration.ConfigurationPath
  commentId: P:OpenSpartan.Grunt.Models.HaloInfinite.Configuration.ConfigurationPath
  id: ConfigurationPath
  parent: OpenSpartan.Grunt.Models.HaloInfinite.Configuration
  langs:
  - csharp
  name: ConfigurationPath
  nameWithType: Configuration.ConfigurationPath
  fullName: OpenSpartan.Grunt.Models.HaloInfinite.Configuration.ConfigurationPath
  type: Property
  assemblies:
  - OpenSpartan.Grunt
  namespace: OpenSpartan.Grunt.Models.HaloInfinite
  syntax:
    content: public string ConfigurationPath { get; set; }
    return:
      type: System.String
      description: ''
    content.csharp: public string ConfigurationPath { get; set; }
  overload: OpenSpartan.Grunt.Models.HaloInfinite.Configuration.ConfigurationPath*
  exceptions: []
  modifiers.csharp:
  - public
  - get
  - set
  monikers:
  - net6.0
references:
- uid: OpenSpartan.Grunt.Models.HaloInfinite
  commentId: N:OpenSpartan.Grunt.Models.HaloInfinite
  isExternal: false
  name: OpenSpartan.Grunt.Models.HaloInfinite
  nameWithType: OpenSpartan.Grunt.Models.HaloInfinite
  fullName: OpenSpartan.Grunt.Models.HaloInfinite
  type: namespace
- uid: System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: OpenSpartan.Grunt.Models.HaloInfinite.Configuration.#ctor
  parent: OpenSpartan.Grunt.Models.HaloInfinite.Configuration
  isExternal: false
  name: Configuration()
  nameWithType: Configuration.Configuration()
  fullName: OpenSpartan.Grunt.Models.HaloInfinite.Configuration.Configuration()
  type: constructor
- uid: OpenSpartan.Grunt.Models.HaloInfinite.Configuration.ConfigurationId
  parent: OpenSpartan.Grunt.Models.HaloInfinite.Configuration
  isExternal: false
  name: ConfigurationId
  nameWithType: Configuration.ConfigurationId
  fullName: OpenSpartan.Grunt.Models.HaloInfinite.Configuration.ConfigurationId
  type: property
- uid: System.Int32
  parent: System
  isExternal: true
  name: Int32
  nameWithType: Int32
  fullName: System.Int32
- uid: OpenSpartan.Grunt.Models.HaloInfinite.Configuration.ConfigurationPath
  parent: OpenSpartan.Grunt.Models.HaloInfinite.Configuration
  isExternal: false
  name: ConfigurationPath
  nameWithType: Configuration.ConfigurationPath
  fullName: OpenSpartan.Grunt.Models.HaloInfinite.Configuration.ConfigurationPath
  type: property
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: OpenSpartan.Grunt.Models.HaloInfinite.Configuration.#ctor*
  commentId: Overload:OpenSpartan.Grunt.Models.HaloInfinite.Configuration.#ctor
  parent: OpenSpartan.Grunt.Models.HaloInfinite.Configuration
  isExternal: false
  name: Configuration
  nameWithType: Configuration.Configuration
  fullName: OpenSpartan.Grunt.Models.HaloInfinite.Configuration.Configuration
  monikers:
  - net6.0
  type: constructor
- uid: OpenSpartan.Grunt.Models.HaloInfinite.Configuration.ConfigurationId*
  commentId: Overload:OpenSpartan.Grunt.Models.HaloInfinite.Configuration.ConfigurationId
  parent: OpenSpartan.Grunt.Models.HaloInfinite.Configuration
  isExternal: false
  name: ConfigurationId
  nameWithType: Configuration.ConfigurationId
  fullName: OpenSpartan.Grunt.Models.HaloInfinite.Configuration.ConfigurationId
  monikers:
  - net6.0
  type: property
- uid: OpenSpartan.Grunt.Models.HaloInfinite.Configuration.ConfigurationPath*
  commentId: Overload:OpenSpartan.Grunt.Models.HaloInfinite.Configuration.ConfigurationPath
  parent: OpenSpartan.Grunt.Models.HaloInfinite.Configuration
  isExternal: false
  name: ConfigurationPath
  nameWithType: Configuration.ConfigurationPath
  fullName: OpenSpartan.Grunt.Models.HaloInfinite.Configuration.ConfigurationPath
  monikers:
  - net6.0
  type: property
