### YamlMime:ManagedReference
items:
- uid: Grunt.Models.HaloInfinite.OverrideSettings
  commentId: T:Grunt.Models.HaloInfinite.OverrideSettings
  id: OverrideSettings
  children:
  - Grunt.Models.HaloInfinite.OverrideSettings.#ctor
  - Grunt.Models.HaloInfinite.OverrideSettings.SpecControlAsyncCompute
  langs:
  - csharp
  name: OverrideSettings
  nameWithType: Grunt.Models.HaloInfinite.OverrideSettings
  fullName: Grunt.Models.HaloInfinite.OverrideSettings
  type: Class
  assemblies:
  - Grunt
  namespace: Grunt.Models.HaloInfinite
  syntax:
    content: public class OverrideSettings
    content.csharp: public class OverrideSettings
  inheritance:
  - System.Object
  implements: []
  inheritedMembers: []
  modifiers.csharp:
  - public
  monikers:
  - net6.0
  _op_AssemblyMonikerMapping:
    Grunt:
    - net6.0
- uid: Grunt.Models.HaloInfinite.OverrideSettings.#ctor
  commentId: M:Grunt.Models.HaloInfinite.OverrideSettings.#ctor
  id: '#ctor'
  parent: Grunt.Models.HaloInfinite.OverrideSettings
  langs:
  - csharp
  name: OverrideSettings()
  nameWithType: OverrideSettings.OverrideSettings()
  fullName: Grunt.Models.HaloInfinite.OverrideSettings.OverrideSettings()
  type: Constructor
  assemblies:
  - Grunt
  namespace: Grunt.Models.HaloInfinite
  syntax:
    content: public OverrideSettings ();
    parameters: []
    content.csharp: public OverrideSettings ();
  overload: Grunt.Models.HaloInfinite.OverrideSettings.#ctor*
  exceptions: []
  modifiers.csharp:
  - public
  monikers:
  - net6.0
- uid: Grunt.Models.HaloInfinite.OverrideSettings.SpecControlAsyncCompute
  commentId: P:Grunt.Models.HaloInfinite.OverrideSettings.SpecControlAsyncCompute
  id: SpecControlAsyncCompute
  parent: Grunt.Models.HaloInfinite.OverrideSettings
  langs:
  - csharp
  name: SpecControlAsyncCompute
  nameWithType: OverrideSettings.SpecControlAsyncCompute
  fullName: Grunt.Models.HaloInfinite.OverrideSettings.SpecControlAsyncCompute
  type: Property
  assemblies:
  - Grunt
  namespace: Grunt.Models.HaloInfinite
  syntax:
    content: >-
      [[Newtonsoft.Json.JsonProperty("spec_control_async_compute")]]

      public bool SpecControlAsyncCompute { get; set; }
    return:
      type: System.Boolean
      description: ''
    content.csharp: >-
      [[Newtonsoft.Json.JsonProperty("spec_control_async_compute")]]

      public bool SpecControlAsyncCompute { get; set; }
  overload: Grunt.Models.HaloInfinite.OverrideSettings.SpecControlAsyncCompute*
  exceptions: []
  attributes:
  - type: '[Newtonsoft.Json.JsonPropertyAttribute'
  modifiers.csharp:
  - public
  - get
  - set
  monikers:
  - net6.0
references:
- uid: Grunt.Models.HaloInfinite
  commentId: N:Grunt.Models.HaloInfinite
  isExternal: false
  name: Grunt.Models.HaloInfinite
  nameWithType: Grunt.Models.HaloInfinite
  fullName: Grunt.Models.HaloInfinite
  type: namespace
- uid: System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: Grunt.Models.HaloInfinite.OverrideSettings.#ctor
  parent: Grunt.Models.HaloInfinite.OverrideSettings
  isExternal: false
  name: OverrideSettings()
  nameWithType: OverrideSettings.OverrideSettings()
  fullName: Grunt.Models.HaloInfinite.OverrideSettings.OverrideSettings()
  type: constructor
- uid: Grunt.Models.HaloInfinite.OverrideSettings.SpecControlAsyncCompute
  parent: Grunt.Models.HaloInfinite.OverrideSettings
  isExternal: false
  name: SpecControlAsyncCompute
  nameWithType: OverrideSettings.SpecControlAsyncCompute
  fullName: Grunt.Models.HaloInfinite.OverrideSettings.SpecControlAsyncCompute
  type: property
- uid: System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: Grunt.Models.HaloInfinite.OverrideSettings.#ctor*
  commentId: Overload:Grunt.Models.HaloInfinite.OverrideSettings.#ctor
  parent: Grunt.Models.HaloInfinite.OverrideSettings
  isExternal: false
  name: OverrideSettings
  nameWithType: OverrideSettings.OverrideSettings
  fullName: Grunt.Models.HaloInfinite.OverrideSettings.OverrideSettings
  monikers:
  - net6.0
  type: constructor
- uid: Grunt.Models.HaloInfinite.OverrideSettings.SpecControlAsyncCompute*
  commentId: Overload:Grunt.Models.HaloInfinite.OverrideSettings.SpecControlAsyncCompute
  parent: Grunt.Models.HaloInfinite.OverrideSettings
  isExternal: false
  name: SpecControlAsyncCompute
  nameWithType: OverrideSettings.SpecControlAsyncCompute
  fullName: Grunt.Models.HaloInfinite.OverrideSettings.SpecControlAsyncCompute
  monikers:
  - net6.0
  type: property
