### YamlMime:ManagedReference
items:
- uid: Grunt.Models.HaloInfinite.OEConfiguration
  commentId: T:Grunt.Models.HaloInfinite.OEConfiguration
  id: OEConfiguration
  children:
  - Grunt.Models.HaloInfinite.OEConfiguration.#ctor
  - Grunt.Models.HaloInfinite.OEConfiguration.Message
  langs:
  - csharp
  name: OEConfiguration
  nameWithType: Grunt.Models.HaloInfinite.OEConfiguration
  fullName: Grunt.Models.HaloInfinite.OEConfiguration
  type: Class
  assemblies:
  - Grunt
  namespace: Grunt.Models.HaloInfinite
  syntax:
    content: public class OEConfiguration
    content.csharp: public class OEConfiguration
  inheritance:
  - System.Object
  implements: []
  inheritedMembers: []
  modifiers.csharp:
  - public
  monikers:
  - net6.0
  _op_AssemblyMonikerMapping:
    Grunt:
    - net6.0
- uid: Grunt.Models.HaloInfinite.OEConfiguration.#ctor
  commentId: M:Grunt.Models.HaloInfinite.OEConfiguration.#ctor
  id: '#ctor'
  parent: Grunt.Models.HaloInfinite.OEConfiguration
  langs:
  - csharp
  name: OEConfiguration()
  nameWithType: OEConfiguration.OEConfiguration()
  fullName: Grunt.Models.HaloInfinite.OEConfiguration.OEConfiguration()
  type: Constructor
  assemblies:
  - Grunt
  namespace: Grunt.Models.HaloInfinite
  syntax:
    content: public OEConfiguration ();
    parameters: []
    content.csharp: public OEConfiguration ();
  overload: Grunt.Models.HaloInfinite.OEConfiguration.#ctor*
  exceptions: []
  modifiers.csharp:
  - public
  monikers:
  - net6.0
- uid: Grunt.Models.HaloInfinite.OEConfiguration.Message
  commentId: P:Grunt.Models.HaloInfinite.OEConfiguration.Message
  id: Message
  parent: Grunt.Models.HaloInfinite.OEConfiguration
  langs:
  - csharp
  name: Message
  nameWithType: OEConfiguration.Message
  fullName: Grunt.Models.HaloInfinite.OEConfiguration.Message
  type: Property
  assemblies:
  - Grunt
  namespace: Grunt.Models.HaloInfinite
  syntax:
    content: public Grunt.Models.HaloInfinite.DisplayString Message { get; set; }
    return:
      type: Grunt.Models.HaloInfinite.DisplayString
      description: ''
    content.csharp: public Grunt.Models.HaloInfinite.DisplayString Message { get; set; }
  overload: Grunt.Models.HaloInfinite.OEConfiguration.Message*
  exceptions: []
  modifiers.csharp:
  - public
  - get
  - set
  monikers:
  - net6.0
references:
- uid: Grunt.Models.HaloInfinite
  commentId: N:Grunt.Models.HaloInfinite
  isExternal: false
  name: Grunt.Models.HaloInfinite
  nameWithType: Grunt.Models.HaloInfinite
  fullName: Grunt.Models.HaloInfinite
  type: namespace
- uid: System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: Grunt.Models.HaloInfinite.OEConfiguration.#ctor
  parent: Grunt.Models.HaloInfinite.OEConfiguration
  isExternal: false
  name: OEConfiguration()
  nameWithType: OEConfiguration.OEConfiguration()
  fullName: Grunt.Models.HaloInfinite.OEConfiguration.OEConfiguration()
  type: constructor
- uid: Grunt.Models.HaloInfinite.OEConfiguration.Message
  parent: Grunt.Models.HaloInfinite.OEConfiguration
  isExternal: false
  name: Message
  nameWithType: OEConfiguration.Message
  fullName: Grunt.Models.HaloInfinite.OEConfiguration.Message
  type: property
- uid: Grunt.Models.HaloInfinite.DisplayString
  parent: Grunt.Models.HaloInfinite
  isExternal: false
  name: DisplayString
  nameWithType: DisplayString
  fullName: Grunt.Models.HaloInfinite.DisplayString
- uid: Grunt.Models.HaloInfinite.OEConfiguration.#ctor*
  commentId: Overload:Grunt.Models.HaloInfinite.OEConfiguration.#ctor
  parent: Grunt.Models.HaloInfinite.OEConfiguration
  isExternal: false
  name: OEConfiguration
  nameWithType: OEConfiguration.OEConfiguration
  fullName: Grunt.Models.HaloInfinite.OEConfiguration.OEConfiguration
  monikers:
  - net6.0
  type: constructor
- uid: Grunt.Models.HaloInfinite.OEConfiguration.Message*
  commentId: Overload:Grunt.Models.HaloInfinite.OEConfiguration.Message
  parent: Grunt.Models.HaloInfinite.OEConfiguration
  isExternal: false
  name: Message
  nameWithType: OEConfiguration.Message
  fullName: Grunt.Models.HaloInfinite.OEConfiguration.Message
  monikers:
  - net6.0
  type: property
