### YamlMime:ManagedReference
items:
- uid: Grunt.Models.ClientConfiguration
  commentId: T:Grunt.Models.ClientConfiguration
  id: ClientConfiguration
  children:
  - Grunt.Models.ClientConfiguration.#ctor
  - Grunt.Models.ClientConfiguration.ClientId
  - Grunt.Models.ClientConfiguration.ClientSecret
  - Grunt.Models.ClientConfiguration.RedirectUrl
  langs:
  - csharp
  name: ClientConfiguration
  nameWithType: Grunt.Models.ClientConfiguration
  fullName: Grunt.Models.ClientConfiguration
  type: Class
  assemblies:
  - Grunt
  namespace: Grunt.Models
  syntax:
    content: public class ClientConfiguration
    content.csharp: public class ClientConfiguration
  inheritance:
  - System.Object
  implements: []
  inheritedMembers: []
  modifiers.csharp:
  - public
  monikers:
  - net6.0
  _op_AssemblyMonikerMapping:
    Grunt:
    - net6.0
- uid: Grunt.Models.ClientConfiguration.#ctor
  commentId: M:Grunt.Models.ClientConfiguration.#ctor
  id: '#ctor'
  parent: Grunt.Models.ClientConfiguration
  langs:
  - csharp
  name: ClientConfiguration()
  nameWithType: ClientConfiguration.ClientConfiguration()
  fullName: Grunt.Models.ClientConfiguration.ClientConfiguration()
  type: Constructor
  assemblies:
  - Grunt
  namespace: Grunt.Models
  syntax:
    content: public ClientConfiguration ();
    parameters: []
    content.csharp: public ClientConfiguration ();
  overload: Grunt.Models.ClientConfiguration.#ctor*
  exceptions: []
  modifiers.csharp:
  - public
  monikers:
  - net6.0
- uid: Grunt.Models.ClientConfiguration.ClientId
  commentId: P:Grunt.Models.ClientConfiguration.ClientId
  id: ClientId
  parent: Grunt.Models.ClientConfiguration
  langs:
  - csharp
  name: ClientId
  nameWithType: ClientConfiguration.ClientId
  fullName: Grunt.Models.ClientConfiguration.ClientId
  type: Property
  assemblies:
  - Grunt
  namespace: Grunt.Models
  syntax:
    content: >-
      [[System.Text.Json.Serialization.JsonPropertyName("client_id")]]

      public string ClientId { get; set; }
    return:
      type: System.String
      description: ''
    content.csharp: >-
      [[System.Text.Json.Serialization.JsonPropertyName("client_id")]]

      public string ClientId { get; set; }
  overload: Grunt.Models.ClientConfiguration.ClientId*
  exceptions: []
  attributes:
  - type: '[System.Text.Json.Serialization.JsonPropertyNameAttribute'
  modifiers.csharp:
  - public
  - get
  - set
  monikers:
  - net6.0
- uid: Grunt.Models.ClientConfiguration.ClientSecret
  commentId: P:Grunt.Models.ClientConfiguration.ClientSecret
  id: ClientSecret
  parent: Grunt.Models.ClientConfiguration
  langs:
  - csharp
  name: ClientSecret
  nameWithType: ClientConfiguration.ClientSecret
  fullName: Grunt.Models.ClientConfiguration.ClientSecret
  type: Property
  assemblies:
  - Grunt
  namespace: Grunt.Models
  syntax:
    content: >-
      [[System.Text.Json.Serialization.JsonPropertyName("client_secret")]]

      public string ClientSecret { get; set; }
    return:
      type: System.String
      description: ''
    content.csharp: >-
      [[System.Text.Json.Serialization.JsonPropertyName("client_secret")]]

      public string ClientSecret { get; set; }
  overload: Grunt.Models.ClientConfiguration.ClientSecret*
  exceptions: []
  attributes:
  - type: '[System.Text.Json.Serialization.JsonPropertyNameAttribute'
  modifiers.csharp:
  - public
  - get
  - set
  monikers:
  - net6.0
- uid: Grunt.Models.ClientConfiguration.RedirectUrl
  commentId: P:Grunt.Models.ClientConfiguration.RedirectUrl
  id: RedirectUrl
  parent: Grunt.Models.ClientConfiguration
  langs:
  - csharp
  name: RedirectUrl
  nameWithType: ClientConfiguration.RedirectUrl
  fullName: Grunt.Models.ClientConfiguration.RedirectUrl
  type: Property
  assemblies:
  - Grunt
  namespace: Grunt.Models
  syntax:
    content: >-
      [[System.Text.Json.Serialization.JsonPropertyName("redirect_url")]]

      public string RedirectUrl { get; set; }
    return:
      type: System.String
      description: ''
    content.csharp: >-
      [[System.Text.Json.Serialization.JsonPropertyName("redirect_url")]]

      public string RedirectUrl { get; set; }
  overload: Grunt.Models.ClientConfiguration.RedirectUrl*
  exceptions: []
  attributes:
  - type: '[System.Text.Json.Serialization.JsonPropertyNameAttribute'
  modifiers.csharp:
  - public
  - get
  - set
  monikers:
  - net6.0
references:
- uid: Grunt.Models
  commentId: N:Grunt.Models
  isExternal: false
  name: Grunt.Models
  nameWithType: Grunt.Models
  fullName: Grunt.Models
  type: namespace
- uid: System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: Grunt.Models.ClientConfiguration.#ctor
  parent: Grunt.Models.ClientConfiguration
  isExternal: false
  name: ClientConfiguration()
  nameWithType: ClientConfiguration.ClientConfiguration()
  fullName: Grunt.Models.ClientConfiguration.ClientConfiguration()
  type: constructor
- uid: Grunt.Models.ClientConfiguration.ClientId
  parent: Grunt.Models.ClientConfiguration
  isExternal: false
  name: ClientId
  nameWithType: ClientConfiguration.ClientId
  fullName: Grunt.Models.ClientConfiguration.ClientId
  type: property
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: Grunt.Models.ClientConfiguration.ClientSecret
  parent: Grunt.Models.ClientConfiguration
  isExternal: false
  name: ClientSecret
  nameWithType: ClientConfiguration.ClientSecret
  fullName: Grunt.Models.ClientConfiguration.ClientSecret
  type: property
- uid: Grunt.Models.ClientConfiguration.RedirectUrl
  parent: Grunt.Models.ClientConfiguration
  isExternal: false
  name: RedirectUrl
  nameWithType: ClientConfiguration.RedirectUrl
  fullName: Grunt.Models.ClientConfiguration.RedirectUrl
  type: property
- uid: Grunt.Models.ClientConfiguration.#ctor*
  commentId: Overload:Grunt.Models.ClientConfiguration.#ctor
  parent: Grunt.Models.ClientConfiguration
  isExternal: false
  name: ClientConfiguration
  nameWithType: ClientConfiguration.ClientConfiguration
  fullName: Grunt.Models.ClientConfiguration.ClientConfiguration
  monikers:
  - net6.0
  type: constructor
- uid: Grunt.Models.ClientConfiguration.ClientId*
  commentId: Overload:Grunt.Models.ClientConfiguration.ClientId
  parent: Grunt.Models.ClientConfiguration
  isExternal: false
  name: ClientId
  nameWithType: ClientConfiguration.ClientId
  fullName: Grunt.Models.ClientConfiguration.ClientId
  monikers:
  - net6.0
  type: property
- uid: Grunt.Models.ClientConfiguration.ClientSecret*
  commentId: Overload:Grunt.Models.ClientConfiguration.ClientSecret
  parent: Grunt.Models.ClientConfiguration
  isExternal: false
  name: ClientSecret
  nameWithType: ClientConfiguration.ClientSecret
  fullName: Grunt.Models.ClientConfiguration.ClientSecret
  monikers:
  - net6.0
  type: property
- uid: Grunt.Models.ClientConfiguration.RedirectUrl*
  commentId: Overload:Grunt.Models.ClientConfiguration.RedirectUrl
  parent: Grunt.Models.ClientConfiguration
  isExternal: false
  name: RedirectUrl
  nameWithType: ClientConfiguration.RedirectUrl
  fullName: Grunt.Models.ClientConfiguration.RedirectUrl
  monikers:
  - net6.0
  type: property
